# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 9999
    connection-timeout: 5000
    context-path: /
 
#文件保存路径
file_save_path: /opt/modeViewServer/upfile/
#模型  zip文件 生成、打包的的目录
zip:
    modeFileDestPath: /opt/modeViewServer/package/
# 临时文件目录
uploadTempDir: E:/uploadTempDir
generateTempDir: E:/generateTempDir
exe_dir: /lib/ 



spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: oracle.jdbc.driver.OracleDriver
        druid:
            first:  #数据源1
                url: jdbc:oracle:thin:@172.16.10.45:1521:orcl
                username: DEVTEST
                password: DEVTEST
            second:  #数据源2
                url: jdbc:oracle:thin:@172.16.10.53:1521:orcl12
                username: api
                password: api
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
